# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_ConsiderationApplication.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class ViewConsiderationApplication(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(873, 518)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 20, 421, 481))
        self.frame.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.463, y1:0.0108696, x2:0.482852, y2:1, stop:1 rgba(195, 168, 101, 255));\n"
"border-radius: 30px;\n"
"border: 2px solid gray")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.textEdit_delivery = QtWidgets.QTextEdit(self.frame)
        self.textEdit_delivery.setGeometry(QtCore.QRect(175, 160, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.textEdit_delivery.setFont(font)
        self.textEdit_delivery.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"border: 2px solid gray")
        self.textEdit_delivery.setReadOnly(True)
        self.textEdit_delivery.setObjectName("textEdit_delivery")
        self.label_description = QtWidgets.QLabel(self.frame)
        self.label_description.setGeometry(QtCore.QRect(45, 230, 111, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_description.setFont(font)
        self.label_description.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.463, y1:0.0108696, x2:0.482852, y2:1, stop:1 rgba(195, 168, 101, 255));\n"
"border: 0px")
        self.label_description.setObjectName("label_description")
        self.label_weight = QtWidgets.QLabel(self.frame)
        self.label_weight.setGeometry(QtCore.QRect(85, 301, 71, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_weight.setFont(font)
        self.label_weight.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.463, y1:0.0108696, x2:0.482852, y2:1, stop:1 rgba(195, 168, 101, 255));\n"
"border: 0px")
        self.label_weight.setObjectName("label_weight")
        self.textEdit_description = QtWidgets.QTextEdit(self.frame)
        self.textEdit_description.setGeometry(QtCore.QRect(175, 230, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.textEdit_description.setFont(font)
        self.textEdit_description.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"border: 2px solid gray")
        self.textEdit_description.setReadOnly(True)
        self.textEdit_description.setObjectName("textEdit_description")
        self.lineEdit_weight = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_weight.setGeometry(QtCore.QRect(175, 300, 211, 22))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lineEdit_weight.setFont(font)
        self.lineEdit_weight.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"border: 2px solid gray")
        self.lineEdit_weight.setReadOnly(True)
        self.lineEdit_weight.setObjectName("lineEdit_weight")
        self.pushButton_Back = QtWidgets.QPushButton(self.frame)
        self.pushButton_Back.setGeometry(QtCore.QRect(10, 430, 391, 28))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Back.setFont(font)
        self.pushButton_Back.setStyleSheet("\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"border: 2px solid gray")
        self.pushButton_Back.setObjectName("pushButton_Back")
        self.label_date = QtWidgets.QLabel(self.frame)
        self.label_date.setGeometry(QtCore.QRect(10, 49, 141, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_date.setFont(font)
        self.label_date.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.463, y1:0.0108696, x2:0.482852, y2:1, stop:1 rgba(195, 168, 101, 255));\n"
"border: 0px")
        self.label_date.setObjectName("label_date")
        self.lineEdit_date = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_date.setGeometry(QtCore.QRect(170, 50, 211, 22))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lineEdit_date.setFont(font)
        self.lineEdit_date.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"border: 2px solid gray")
        self.lineEdit_date.setReadOnly(True)
        self.lineEdit_date.setObjectName("lineEdit_date")
        self.labe_dispatch = QtWidgets.QLabel(self.frame)
        self.labe_dispatch.setGeometry(QtCore.QRect(30, 90, 121, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.labe_dispatch.setFont(font)
        self.labe_dispatch.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.463, y1:0.0108696, x2:0.482852, y2:1, stop:1 rgba(195, 168, 101, 255));\n"
"border: 0px")
        self.labe_dispatch.setObjectName("labe_dispatch")
        self.pushButton_MakeOrder = QtWidgets.QPushButton(self.frame)
        self.pushButton_MakeOrder.setGeometry(QtCore.QRect(10, 350, 391, 28))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_MakeOrder.setFont(font)
        self.pushButton_MakeOrder.setStyleSheet("\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"border: 2px solid gray")
        self.pushButton_MakeOrder.setObjectName("pushButton_MakeOrder")
        self.textEdit_dispatch = QtWidgets.QTextEdit(self.frame)
        self.textEdit_dispatch.setGeometry(QtCore.QRect(170, 90, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.textEdit_dispatch.setFont(font)
        self.textEdit_dispatch.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"border: 2px solid gray")
        self.textEdit_dispatch.setReadOnly(True)
        self.textEdit_dispatch.setObjectName("textEdit_dispatch")
        self.pushButton_Deny = QtWidgets.QPushButton(self.frame)
        self.pushButton_Deny.setGeometry(QtCore.QRect(10, 390, 391, 28))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Deny.setFont(font)
        self.pushButton_Deny.setStyleSheet("\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"border: 2px solid gray")
        self.pushButton_Deny.setObjectName("pushButton_Deny")
        self.label_delivery = QtWidgets.QLabel(self.frame)
        self.label_delivery.setGeometry(QtCore.QRect(29, 160, 121, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_delivery.setFont(font)
        self.label_delivery.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.463, y1:0.0108696, x2:0.482852, y2:1, stop:1 rgba(195, 168, 101, 255));\n"
"border: 0px")
        self.label_delivery.setObjectName("label_delivery")
        self.label_MidleInfo = QtWidgets.QLabel(self.frame)
        self.label_MidleInfo.setGeometry(QtCore.QRect(110, 10, 201, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_MidleInfo.setFont(font)
        self.label_MidleInfo.setStyleSheet("border: 0px")
        self.label_MidleInfo.setObjectName("label_MidleInfo")
        self.textEdit_delivery.raise_()
        self.label_description.raise_()
        self.textEdit_description.raise_()
        self.label_weight.raise_()
        self.lineEdit_weight.raise_()
        self.pushButton_Back.raise_()
        self.label_date.raise_()
        self.lineEdit_date.raise_()
        self.labe_dispatch.raise_()
        self.pushButton_MakeOrder.raise_()
        self.textEdit_dispatch.raise_()
        self.pushButton_Deny.raise_()
        self.label_delivery.raise_()
        self.label_MidleInfo.raise_()
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(440, 20, 421, 181))
        self.frame_2.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.463, y1:0.0108696, x2:0.482852, y2:1, stop:1 rgba(195, 168, 101, 255));\n"
"border-radius: 30px;\n"
"border: 2px solid gray")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_Client = QtWidgets.QLabel(self.frame_2)
        self.label_Client.setGeometry(QtCore.QRect(180, 10, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_Client.setFont(font)
        self.label_Client.setStyleSheet("border: 0px")
        self.label_Client.setObjectName("label_Client")
        self.label_FirstName = QtWidgets.QLabel(self.frame_2)
        self.label_FirstName.setGeometry(QtCore.QRect(100, 55, 31, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_FirstName.setFont(font)
        self.label_FirstName.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.463, y1:0.0108696, x2:0.482852, y2:1, stop:1 rgba(195, 168, 101, 255));\n"
"border: 0px")
        self.label_FirstName.setObjectName("label_FirstName")
        self.textEdit_FirstName = QtWidgets.QTextEdit(self.frame_2)
        self.textEdit_FirstName.setGeometry(QtCore.QRect(150, 55, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.textEdit_FirstName.setFont(font)
        self.textEdit_FirstName.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"border: 2px solid gray")
        self.textEdit_FirstName.setReadOnly(True)
        self.textEdit_FirstName.setObjectName("textEdit_FirstName")
        self.label_LastName = QtWidgets.QLabel(self.frame_2)
        self.label_LastName.setGeometry(QtCore.QRect(70, 105, 61, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_LastName.setFont(font)
        self.label_LastName.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.463, y1:0.0108696, x2:0.482852, y2:1, stop:1 rgba(195, 168, 101, 255));\n"
"border: 0px")
        self.label_LastName.setObjectName("label_LastName")
        self.textEdit_LastName = QtWidgets.QTextEdit(self.frame_2)
        self.textEdit_LastName.setGeometry(QtCore.QRect(150, 105, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.textEdit_LastName.setFont(font)
        self.textEdit_LastName.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"border: 2px solid gray")
        self.textEdit_LastName.setReadOnly(True)
        self.textEdit_LastName.setObjectName("textEdit_LastName")
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(440, 210, 421, 181))
        self.frame_3.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.463, y1:0.0108696, x2:0.482852, y2:1, stop:1 rgba(195, 168, 101, 255));\n"
"border-radius: 30px;\n"
"border: 2px solid gray")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_CustomerContacts = QtWidgets.QLabel(self.frame_3)
        self.label_CustomerContacts.setGeometry(QtCore.QRect(140, 10, 161, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_CustomerContacts.setFont(font)
        self.label_CustomerContacts.setStyleSheet("border: 0px")
        self.label_CustomerContacts.setObjectName("label_CustomerContacts")
        self.label_Phone = QtWidgets.QLabel(self.frame_3)
        self.label_Phone.setGeometry(QtCore.QRect(20, 55, 121, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_Phone.setFont(font)
        self.label_Phone.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.463, y1:0.0108696, x2:0.482852, y2:1, stop:1 rgba(195, 168, 101, 255));\n"
"border: 0px")
        self.label_Phone.setObjectName("label_Phone")
        self.textEdit_Phone = QtWidgets.QTextEdit(self.frame_3)
        self.textEdit_Phone.setGeometry(QtCore.QRect(150, 55, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.textEdit_Phone.setFont(font)
        self.textEdit_Phone.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"border: 2px solid gray")
        self.textEdit_Phone.setReadOnly(True)
        self.textEdit_Phone.setObjectName("textEdit_Phone")
        self.label_Email = QtWidgets.QLabel(self.frame_3)
        self.label_Email.setGeometry(QtCore.QRect(100, 105, 41, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_Email.setFont(font)
        self.label_Email.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.463, y1:0.0108696, x2:0.482852, y2:1, stop:1 rgba(195, 168, 101, 255));\n"
"border: 0px")
        self.label_Email.setObjectName("label_Email")
        self.textEdit_Email = QtWidgets.QTextEdit(self.frame_3)
        self.textEdit_Email.setGeometry(QtCore.QRect(150, 105, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.textEdit_Email.setFont(font)
        self.textEdit_Email.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"border: 2px solid gray")
        self.textEdit_Email.setReadOnly(True)
        self.textEdit_Email.setObjectName("textEdit_Email")
        # MainWindow.setCentralWidget(self.centralwidget)
        # self.menubar = QtWidgets.QMenuBar(MainWindow)
        # self.menubar.setGeometry(QtCore.QRect(0, 0, 873, 21))
        # self.menubar.setObjectName("menubar")
        # MainWindow.setMenuBar(self.menubar)
        # self.statusbar = QtWidgets.QStatusBar(MainWindow)
        # self.statusbar.setObjectName("statusbar")
        # MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.textEdit_delivery.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:7.8pt;\"><br /></p></body></html>"))
        self.label_description.setText(_translate("MainWindow", "Описание груза"))
        self.label_weight.setText(_translate("MainWindow", "Вес груза"))
        self.textEdit_description.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:7.8pt;\"><br /></p></body></html>"))
        self.pushButton_Back.setText(_translate("MainWindow", "Назад"))
        self.label_date.setText(_translate("MainWindow", "Дата подачи заявки:"))
        self.lineEdit_date.setText(_translate("MainWindow", "fsdgfdgfdg"))
        self.labe_dispatch.setText(_translate("MainWindow", "Aдрес Отправки:"))
        self.pushButton_MakeOrder.setText(_translate("MainWindow", "Перейти к оформлению заказа"))
        self.textEdit_dispatch.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\';\">dfgdfgdfgdfgfdg</span></p></body></html>"))
        self.pushButton_Deny.setText(_translate("MainWindow", "Отказать"))
        self.label_delivery.setText(_translate("MainWindow", "Aдрес доставки:"))
        self.label_MidleInfo.setText(_translate("MainWindow", "Основная информация"))
        self.label_Client.setText(_translate("MainWindow", "Клиент"))
        self.label_FirstName.setText(_translate("MainWindow", "Имя"))
        self.textEdit_FirstName.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:7.8pt;\"><br /></p></body></html>"))
        self.label_LastName.setText(_translate("MainWindow", "Фамилия"))
        self.textEdit_LastName.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:7.8pt;\"><br /></p></body></html>"))
        self.label_CustomerContacts.setText(_translate("MainWindow", "Контакты клиента"))
        self.label_Phone.setText(_translate("MainWindow", "Номер телефона"))
        self.textEdit_Phone.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:7.8pt;\"><br /></p></body></html>"))
        self.label_Email.setText(_translate("MainWindow", "Email"))
        self.textEdit_Email.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:7.8pt;\"><br /></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = ViewConsiderationApplication()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
